### ISSUE TITLE
Complete GA4 setup

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#372]
Hey @jonny-wg2 and @Prid13 - there's a call to action form Google to complete the GA4 setup. 

Jonny, should we review this together? 

<img width="1460" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/98818609/ad3cfdbe-8935-4787-91c1-5a5276987319">

**Comment by jonny-wg2** [comment]
All good to go. GA4 was set up already. This setup wizard just notified us that there is some configuration we can do.

I went through the setup wizard and think it's good to go since we don't do any advertisement or leverage the conversion funnels etc.

![image](https://github.com/working-group-two/wgtwo.com/assets/39831372/a43222b6-1972-4b62-a61d-001b8f7abe45)

**Comment by torotimes** [comment]
Great, thanks so much!!
