### ISSUE TITLE
Buttons should have a "on hover" effect to show that it is a button

### ISSUE THREAD

**Issue by lukas-wg2** [working-group-two/wgtwo.com#39]
These elements change when mouse cursor is over them

![onhover](https://user-images.githubusercontent.com/43165886/154470532-c32d915d-74b0-4a62-ba2f-b491c5d076c4.png)

None of the buttons on our webpage change when you mouse over them

![notveryhover](https://user-images.githubusercontent.com/43165886/154470547-17ccba30-4e20-4d5b-80fd-0f9847113c83.png)

**Comment by torotimes** [comment]
@Prid13 I assigned this one to you now. Why don't you have a look at how we might be able to develop a "on hover" effect on buttons? Before you start coding a solution, let's talk about how it might work. You can post suggestions here or we can do it on the phone.

**Comment by Prid13** [comment]
Awesome! Just spent some time making a few mockups of different hover animations, because I couldn't decide which one was best, if any at all.

Here are the suggestions (videos):

## Lighter background color on hover
https://user-images.githubusercontent.com/27897747/186182263-9a831217-d98a-4e18-9ef8-ae4371f7a782.mp4

_

## Move up on hover
https://user-images.githubusercontent.com/27897747/186183495-0a49249e-6da1-4bfe-b702-90800002e4bf.mp4

_

## Border on hover
https://user-images.githubusercontent.com/27897747/186183241-1632028c-148c-4b2d-9a28-79d87db05f90.mp4

https://user-images.githubusercontent.com/27897747/186183343-d1ebb5fe-9f25-4545-a4cf-fbba65d223ac.mp4

_

## Invert + Border on hover
https://user-images.githubusercontent.com/27897747/186183765-a3b96715-79ac-43fe-9b46-427b5090c844.mp4

https://user-images.githubusercontent.com/27897747/186183888-263b49f3-d0e8-4566-9dc1-f1cc629987b6.mp4

---

Personally, I like the last one. What do you think? :)

**Comment by torotimes** [comment]
Great!

I'll take a look tomorrow morning!

**Comment by jonny-wg2** [comment]
Great stuff! I don't think we could go wrong with any option. If I had to choose, option 1 `Lighter background color on hover` is simple and elegant. For the secondary button on the homepage we could adopt the CSS from the header of `Talk to us` 
<img width="256" alt="image" src="https://user-images.githubusercontent.com/39831372/186357475-d60bb77e-51da-43ea-815a-782ba96bc83a.png">

**Comment by torotimes** [comment]
@jonny-wg2 this makes good sense. Are you suggesting that we use the CSS from the header or "Talk to us" for all the buttons throughout the site?

**Comment by jonny-wg2** [comment]
All of the previous examples from @Prid13 were a hover effect on a **dark** colored button. On the homescreen we have the Request a Demo button that is the same CSS as `Talk to us`. So my thinking is we could leverage the same CSS hover for `Talk to us` and use this for the `Request a demo`.
  
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/39831372/186397718-8fe61828-113e-4d26-95bf-cab8c4607a42.png">

**Comment by torotimes** [comment]
Agree.

@Prid13 wanna start implementing? Let us know if you need clarifications.

**Comment by Prid13** [comment]
Good thoughts :)

The lighter background color works great, but it creates a rather awkward "dynamic" where the secondary button feels more "powerful"/"weightier" than the primary button. Take a look at the two buttons on the main page:

https://user-images.githubusercontent.com/27897747/186422799-8dc060d1-ff61-435c-8a70-c3cd8e704101.mp4

That's why I tried putting a different effect on the primary buttons to make them feel like primary buttons on hover:

https://user-images.githubusercontent.com/27897747/186422936-20c16a09-5f86-456c-af9b-6f2ed89d1f80.mp4

That's just my personal opinion though. Any thoughts? Do I move forward with the "Lighter background on hover" :)?

**Comment by lukas-wg2** [comment]
I like the "lighter background color on hover" the most I think. In the last example the border around the darker button stands out a bit much IMO. The primary buttons already stand out enough as primary button, and the the `on hover` on the primary button is still darker than the secondary buttons `on hover`

**Comment by Prid13** [comment]
@lukas-wg2 Thanks for your input, appreciate it. "Lighter background on hover" it is, then 😇👍
